name: Go

on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get install -y git gitk

    - name: Get source and dependencies
      run: |
        git clone https://github.com/godcong/fate
        cd fate
        go mod tidy

    - name: Run 
      run: |
        cd fate
        go run ./cmd/console 

    - name: Create Release
      id: create_release
      uses: ncipollo/release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        artifacts: ""
        allowUpdates: true 
        commit: master 
        tag: make
        body: |
          this is only a latest build from master
          version: https://github.com/godcong/fate/commit
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        prerelease: false
